services:
    # React App
    web:
        container_name: labeling-helper-web
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start:web
        ports:
            - 4201:4201
        networks:
            - internal

    # Express App
    server:
        container_name: labeling-helper-server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run start:server
        ports:
            - 3000:3000
        networks:
            - internal

    # Flutter App
    #    mobile:
    #        extends:
    #            file: docker-compose.base.yml
    #            service: nx-app-base
    #        command: npm run start:mobile
    #        ports:
    #            - 3000:3000

    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        depends_on:
            - web
            - server
        ports:
            - 80:80
        networks:
            - internal

networks:
    internal:

volumes:
    mono-node-modules: null
