name: dev_deploy

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]
    workflow_dispatch:

jobs:
    install-node:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js and npm
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: npm install
              run: |
                  npm install --legacy-peer-deps

    build:
        needs: install-node
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker image
              run: |
                  docker-compose up -d

            - name: Tag Docker image
              run: |
                  docker tag labeling-helper-web:latest "${{ secrets.DOCKERHUB_USERNAME }}/labeling-helper-web:latest"
                  docker tag labeling-helper-server:latest "${{ secrets.DOCKERHUB_USERNAME }}/labeling-helper-server:latest"

            - name: Push Docker Image to Docker hub
              run: |
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/labeling-helper-web:web
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/labeling-helper-server:server

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }} # aws ip 주소
                  username: ${{ secrets.EC2_USERNAME }} # ec2 접속 유저네임
                  key: ${{ secrets.KEY }} # ssh 공개키
                  script: |
                      sudo docker rm -f $(docker ps -qa)
                      sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/labeling-helper-web:web
                      sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/labeling-helper-server:server
                      docker-compose up -d --build
                      docker image prune -f
